-- MY_PROJECT_DEV_PREP_DB/BASE_MODEL/tables/orders.sql
CREATE OR ALTER TABLE MY_PROJECT_DEV_PREP_DB.BASE_MODEL.ORDERS (
	ORDER_ID NUMBER(38,0),
	CUST_ID NUMBER(38,0),
	ORDER_TOTAL NUMBER(10,2),
	ORDER_DATE DATE
);
