"""Discovery, ordering, and validation for the per-env-folder model + LMA.

Naming convention (ONE place — change PROJECT/LAYERS and everything follows):

    database : <PROJECT>_<ENV>_<LAYER>_DB
    folder   : <PROJECT>_<ENV>_<LAYER>_DB/<SCHEMA>/<type>/<name>.sql

The folder name IS the database name.

Object types and deploy order (tables first, then their loaders, then tasks,
then catalog rows — because a task calls the SP that reads the catalog, and
the insert depends on the table existing):

    tables   -> CREATE OR ALTER TABLE           (schema)
    views    -> CREATE OR REPLACE VIEW
    inserts  -> INSERT/transform (the LMA QUERY_STATEMENT)   [data step]
    tasks    -> CREATE TASK IF NOT EXISTS       (only if absent)
    catalog  -> MERGE row into QUERY_CATALOG_TBL (keyed on query_id)

DEV folders are authored (via capture). TST/PRD are generated by convert_env.
"""

import pathlib
import re

REPO_ROOT = pathlib.Path(__file__).parent.parent

PROJECT = "MY_PROJECT"
# Layers that have a repo folder holding deployable object files.
LAYERS = ["PREP", "ANALYTICS", "MD"]

# Deploy order across object types. Data steps (inserts) run after schema.
DEPLOY_ORDER = ["tables", "views", "inserts", "tasks", "catalog"]

# Which object types are "data-affecting" — these trigger a backup and are
# skipped on a no-op redeploy.
DATA_TYPES = {"inserts"}

CREATE_RE = re.compile(
    r"CREATE\s+(?:OR\s+(?:REPLACE|ALTER)\s+)?(?:TABLE|VIEW)\s+"
    r"(?:IF\s+NOT\s+EXISTS\s+)?([A-Z0-9_.]+)",
    re.IGNORECASE,
)
REPLACE_TABLE = re.compile(r"CREATE\s+OR\s+REPLACE\s+TABLE", re.IGNORECASE)
EMPTY_SCHED_RE = re.compile(r"SCHEDULE\s*=\s*'\s*'", re.IGNORECASE)


def db_name(layer, env):
    return f"{PROJECT}_{env.upper()}_{layer.upper()}_DB"


def env_folders(env):
    return [db_name(layer, env) for layer in LAYERS]


def build_manifest(cfg, target=None):
    env = cfg["env"]
    files = []
    for obj_type in DEPLOY_ORDER:
        for folder in env_folders(env):
            root = REPO_ROOT / folder
            if root.exists():
                files.extend(sorted(root.rglob(f"{obj_type}/*.sql")))
    if target:
        files = [f for f in files if target in str(f.relative_to(REPO_ROOT))]
    return files


def object_type(path):
    """The folder directly holding the file: tables/views/inserts/tasks/catalog."""
    return path.parent.name


def validate_no_replace_table(path, raw_text):
    if REPLACE_TABLE.search(raw_text):
        raise ValueError(
            f"{path.relative_to(REPO_ROOT)}: CREATE OR REPLACE TABLE drops data. "
            f"Use CREATE OR ALTER TABLE instead."
        )


def extract_object_name(sql):
    m = CREATE_RE.search(sql)
    if not m:
        raise ValueError("No CREATE TABLE/VIEW statement found")
    return m.group(1).upper()


def derive_expected_name(path, env):
    parts = path.relative_to(REPO_ROOT).parts
    if len(parts) != 4:
        raise ValueError(
            f"{path.relative_to(REPO_ROOT)}: expected "
            f"{PROJECT}_<ENV>_<LAYER>_DB/SCHEMA/TYPE/name.sql"
        )
    db, schema, _obj_type, filename = parts
    prefix = f"{PROJECT}_{env.upper()}_"
    if not db.startswith(prefix) or not db.endswith("_DB"):
        raise ValueError(
            f"{db}: folder must look like {prefix}<LAYER>_DB for env {env}"
        )
    name = pathlib.Path(filename).stem.upper()
    return f"{db}.{schema}.{name}"


def validate_file(path, sql, env):
    """Only structural CREATE files (tables/views) are name-checked against path.

    inserts/tasks/catalog are procedural or data — they legitimately reference
    many objects, so the single-name check doesn't apply. Tasks get one extra
    check: an empty SCHEDULE is invalid and would fail at deploy, so reject it
    here (cheaper as a PR-check failure than a deploy crash).
    """
    if object_type(path) == "tasks" and EMPTY_SCHED_RE.search(sql):
        raise ValueError(
            f"{path.relative_to(REPO_ROOT)}: task has an empty SCHEDULE. "
            f"Set a valid schedule, e.g. USING CRON 45 4 * * * America/Chicago."
        )
    if object_type(path) not in {"tables", "views"}:
        return
    expected = derive_expected_name(path, env)
    actual = extract_object_name(sql)
    if actual != expected:
        raise ValueError(
            f"{path.relative_to(REPO_ROOT)}: DDL creates {actual} "
            f"but path implies {expected}"
        )


def derive_path_from_name(object_name, env, obj_type):
    parts = object_name.upper().split(".")
    if len(parts) != 3:
        raise ValueError(f"{object_name}: expected DB.SCHEMA.OBJECT")
    db, schema, name = parts
    prefix = f"{PROJECT}_{env.upper()}_"
    if not db.startswith(prefix) or not db.endswith("_DB"):
        raise ValueError(f"{db}: expected database like {prefix}<LAYER>_DB")
    return REPO_ROOT / db / schema / obj_type / f"{name.lower()}.sql"
