-- MY_PROJECT_DEV_PREP_DB/BASE_MODEL/tasks/refresh_orders_tsk.sql
CREATE TASK IF NOT EXISTS MY_PROJECT_DEV_PREP_DB.BASE_MODEL.REFRESH_ORDERS_TSK
    WAREHOUSE = COMPUTE_WH
    SCHEDULE = 'using cron 45 4 * * * America/Matamoros'
AS CALL MY_PROJECT_DEV_MD_DB.CATALOG.QUERY_EXECUTION_GENERIC_SP(
    'MY_PROJECT_ORDERS', 'MY_PROJECT', 'MY_PROJECT_DEV_MD_DB.CATALOG', 'MY_PROJECT_DEV_LOG_DB.APP'
);
