-- MY_PROJECT_DEV_MD_DB/CATALOG/catalog/orders.sql
DELETE FROM MY_PROJECT_DEV_MD_DB.CATALOG.QUERY_CATALOG_TBL WHERE QUERY_ID = 'MY_PROJECT_ORDERS';

INSERT INTO MY_PROJECT_DEV_MD_DB.CATALOG.QUERY_CATALOG_TBL
(QUERY_ID, PROJECT, SRC_DB_SCHEMA_TBL, TGT_DB_SCHEMA_TBL, QUERY_STATEMENT,
 INDEX_VALUE, IS_ACTIVE, DB_ENV, LAST_UPDATED_BY, LAST_UPDATED_TS)
VALUES (
 'MY_PROJECT_ORDERS', 'MY_PROJECT',
 'SRC_CRM_DB.RAW.ORDERS',
 'MY_PROJECT_DEV_PREP_DB.BASE_MODEL.ORDERS',
 'INSERT INTO MY_PROJECT_DEV_PREP_DB.BASE_MODEL.ORDERS SELECT ORDER_ID, CUST_ID, ORDER_TOTAL, ORDER_DATE, ORDER_DATE FROM SRC_CRM_DB.RAW.ORDERS;',
 2, 'Y', '__ENV__', '__USER__', current_timestamp(3)
);
