-- MY_PROJECT_DEV_PREP_DB/BASE_MODEL/inserts/orders.sql
-- TARGET: MY_PROJECT_DEV_PREP_DB.BASE_MODEL.ORDERS
INSERT INTO MY_PROJECT_DEV_PREP_DB.BASE_MODEL.ORDERS SELECT ORDER_ID, CUST_ID, ORDER_TOTAL, ORDER_DATE FROM SRC_CRM_DB.RAW.ORDERS;
